### ISSUE TITLE
Token properties should be referable to by Shortname

### ISSUE THREAD

**Issue by kayila** [JamzTheMan/MapTool#100]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Token properties should be able to be referred to in macros by their shortname

**Describe alternatives you've considered**
The `getProperty()` attribute works, but is kind of clunky.

**Additional context**
N/A

**Comment by JamzTheMan** [comment]
Can you elaborate why this would be needed? Short names can have spaces & special characters, so it's really a "Display" name if anything.  And do you mean within other properties or in macros?

That and I don't believe short names have to be unique.

**Comment by kayila** [comment]
The idea was to have the 'property name' viewable in the properties view show the normal property name, and the short name be the name that is referred to in macros. I've now learned that it's the opposite way, so this bug could become an 'enhance documentation' bug.

**Comment by JamzTheMan** [comment]
Got it.

@Phergus may be able to help, hes our wiki guru :)

**Comment by Phergus** [comment]
I knew it was a mistake to get a login for the wiki...

I'll find the documentation on the wiki and see about clarifying it at the very least.

**Comment by Phergus** [comment]
I've updated the Intro to Properties page.  Corrected the note that properties can't have spaces (they can), added some highlighting and reworded the suggestion to not use spaces.  Also added to Short Names section.

http://www.lmwcs.com/rptools/wiki/Introduction_to_Properties

Review and comment if further clarification is needed.

**Comment by JamzTheMan** [comment]
Thanks, you're doing Deneir's work for sure! :)
Now if we could only get the wiki info into md docs in the repo....

Should we close this issue now?

**Comment by kayila** [comment]
Looks good to me. I think it's still worth it to have a getShortName like macro which returns the value of the short name, but the documentation I think is fine at this point.

**Comment by Phergus** [comment]
I agree that it could be handy.  Those not using the statsheet could instead store property descriptions or long names with spaces to use in other places.  Would need a different issue opened.
