### ISSUE TITLE
macro input function should set focus

### ISSUE THREAD

**Issue by kayila** [JamzTheMan/MapTool#103]
When the `input` macro is used, it should automatically focus the first field in the popup box.

Ideally, it should highlight the initial value as well.

**Comment by Phergus** [comment]
It does that for me already in both 1.4.0.5 and 1.4.5.3.  Just tried several different ones in my own game framework.  Always highlights first entry and from there can easily tab through making changes as needed.

**Comment by JamzTheMan** [comment]
me too... I wouldn't mind a empty vs 0 default though...

**Comment by kayila** [comment]
Hmm... For me this wasn't the case. I'll test with another version/os amd see if I can narrow down the cause.

**Comment by JamzTheMan** [comment]
Also, post your input macro sample and I'll test if you want. Maybe just a macro coding issue.

**Comment by Phergus** [comment]
That works as expected on 1.4.0.5/1.4.5.3 under Windows 10/Java 10 for me.

> The problem only occurs with the box that is created by the input macro, and does not exist for the dialog box that appears for unset variables.

Curious but they are probably created differently.  Still that may provide a clue as to why it is happening.  Wonder if it happens on MacOS?

**Comment by Phergus** [comment]
FWIW, the input() dialog on Macs works as expected as well.  So it appears to be a Linux thing.

**Comment by JamzTheMan** [comment]
Are we talking Ubuntu 18.04 or something else?  I can test in a VM but not sure if results would be the same (I expect them to be?) Although things can get screwy when you remote into linux or use VM's depending on various things.

In fact, I hear Windows 10 now supports Ubuntu 18 as a VM (as in hyper-v) and as such wouldn't need to use vmware or anything. There are some benifits to this so been meaning to test it out.  Windows is slowing building in some core linux support.

**Comment by kayila** [comment]
I believe the computer is running Ubuntu 18.04. I'm not in a position right
now where I can check.

**Comment by JamzTheMan** [comment]
np, some people run centOS or debian but by far most are on Ubuntu and usually the latest.  There are way to many flavors to test so I just keep a Ubuntu VM around (and have a debian headless fileserver running but I only test there rarely)

**Comment by auror92** [comment]
i can confirm the problem on Ubuntu 18.04, a bit annoying, would be great if corrected.
