### ISSUE TITLE
Screen capture map and make it a texture/drawable.

### ISSUE THREAD

**Issue by dorpond** [JamzTheMan/MapTool#11]
Create a snipping tool like the one Trevor added to TokenTool, so that we can snip part of a bound map and instantly make that a object/background texture or drawable, so that we can now use that when adding/modifying to the map.

Use cases:
- A bound map has a dead body laying on the floor or doors all over the place. We want to cover that body because it doesn't match our encounter, or we want to cover the doors and put in our own 'swivel doors' in place. There are so many bound maps out there with so many objects on them that don't fit our specific encounter, to cover them quickly and easily in MT without having to pull up the map in Photoshop would greatly speed up map building.

**Comment by JamzTheMan** [comment]
Very useful concept, I'm always drawing over doors to place movable doors... Also sometimes those pesky (S)ecret door markers are hard coded to the map as well...

I'm not sure if the results will be as good as photoshop but I will investigate this!

**Comment by Phergus** [comment]
Something that worked like the Clone tool in GIMP would be nice.  That's what I typically use to get rid of doors (secret or otherwise) and other GM content on maps that weren't made to be player-facing.

**Comment by JamzTheMan** [comment]
Yep. Although I may need to figure out how to feather the clone/texture as well. Usually I clone a floor tile/area then feather it before pasting in Photoshop to make sure there are no hard lines and blends in well.

No sense in doing it if it's obvious something was done on a wall/floor section...

**Comment by Phergus** [comment]
> No sense in doing it if it's obvious something was done on a wall/floor section...
Absolutely.  Smoothly blending in the cloned material will be key.

It may be that Clone in GIMP means something different than what it means in PS.  The feathering is part of the process assuming you use the correct brush settings.  You just click someplace in the source image, e.g. an empty section of floor, and then paint in a different or target area laying down what's in the source area.  If using soft-edged brushes, or with feathering turned on, then it smoothly blends in the new material.  Works fantastic for removing stuff like chests or debris that is on the map as created but you don't want in your version.  Or that you just want to actually replace with objects.

Something that would be cool in MapTool but I'm very used to doing in this in GIMP already.
