### ISSUE TITLE
Java 11 Compatibility

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#112]
**Is your feature request related to a problem? Please describe.**
Now that JRE 10 is not publicly available, running the JAR is problematic.

**Describe the solution you'd like**
MapTool needs to be compatible with OpenJDK 11.

**Describe alternatives you've considered**
Running MapTool using JRE 11 throws missing class exceptions due to FX classes removed from the JRE.

**Comment by Phergus** [comment]
I think you meant "Now that JRE 10 is **no longer** available,..."

Except it is, you just have to go to the archives page.  And have an Oracle account.

**Comment by JamzTheMan** [comment]
True, no longer publicly available? Easily available?

In any case, it's not available for CI and I can't currently build releases.
