### ISSUE TITLE
Edit macro allows pops up an error (Mac user

### ISSUE THREAD

**Issue by OronirL12** [JamzTheMan/MapTool#116]
So, every time I right click > edit macro, it gives this error. This is a nuisance. 

**MapTool Info**
- Version: 1.4.5.3

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Version 10.13.5

![error_nerps1453_editmacro](https://user-images.githubusercontent.com/45273824/49117632-a794bf80-f2a1-11e8-8184-50c6389a619a.jpeg)

**Comment by JamzTheMan** [comment]
I believe this is an issue with Java 10 + JIDE.  I will probably not get a fix in for 1.4.x but should be fixed for 2.0.
