### ISSUE TITLE
Export Campaign As... does not create compatible campaign file.

### ISSUE THREAD

**Issue by Phergus** [JamzTheMan/MapTool#120]
**Description**
Exporting a 1.4.5.4 campaign file to 1.4.0.1 format does not produce a campaign file that can be loaded in 1.4.0.5

Is not filtering out new terrainModifier field from tokens.

**To Reproduce**
1. Load or create a campaign file with tokens.
2. Click on File -> Export -> Campaign As...
3. Click on Export and save campaign.
4. Start MT 1.4.0.5 and attempt to load campaign saved in previous step.
5. Get Error message that campaign file is not readable by this version of MapTool.

**Expected behavior**
Expected it to load.

**Screenshots**
![screenshot 2019-01-03 20 44 04](https://user-images.githubusercontent.com/34379254/50673150-675be780-0f99-11e9-9c5a-e4b112ce1b5a.png)

**MapTool Info**
- Version: 1.4.5.4
- Install: JAR [Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version:  10

**Additional context**
Probably has existed since at least 1.4.5.2.

**Comment by JamzTheMan** [comment]
Ug, thanks. I really should add a Test case for this to run on new builds....
