### ISSUE TITLE
Release Fedora RPMs.

### ISSUE THREAD

**Issue by dracwyrm** [JamzTheMan/MapTool#122]
Hi,

Since you release .deb packages, I was wondering if you could add Fedora RPMs to the download section. I have tried using alien to convert the .deb to .rpm, however, it fails to install.

Thank you,
Jon

**Comment by JamzTheMan** [comment]
In theory this should be possible. I had originally tried creating RPM's under Travis CI and couldn't get it to work. I can try under AppVeyor and see. Javapackager does support it currently but the CI VM's do not support RPM out of the box currently.
