### ISSUE TITLE
Lighting isn't immediately forcing to client

### ISSUE THREAD

**Issue by dorpond** [JamzTheMan/maptool#15]
1.4.1.7 and 1.4.3.20 (note: this problem does not exist in 1.3B91)

Simply put, when lighting is turn on or off on a token (GM side), the changes are not immediately reflected on the client side until a token is clicked. 

**Settings I used in test:**
Start Server: Strict Token Ownership and Restricted Player Impersonation were checked. I also tried both I.View On and Off with no difference.
MT Vision: Night
FOW: On
VBL: Yes, rooms were all traced with VBL.

**Steps:** 
1. Drop some tokens (PC and NPC) in the room
2 Assign a light to a PC token
3. Expose some FOW (I did Control-I)
4. Turn off light on the token from the GM's side
5. Observe that the client can still see the lit up area. (Fail)
6. Move some NPC's around and notice how the client can see them move around. (results of the fail)
7. If a player happens to click on a token, then the lighting changes are finally pushed down and everything goes black. 
8. Conclusion: Screen should have gone black the moment the GM turned off lights - without having to click on anything on the client side.

**Comment by dorpond** [comment]
This is an important bug to squish in my eyes - it has the potential of spoiling a game when players can see the DM moving stuff around, all because they didn't click on their token to get the vision updates.

**Comment by JamzTheMan** [comment]
I'm going to need some more info/example/video.  I just tested this with specified settings with 1.4b91, 1.4.0.5 and 1.4.4.0. Turning the light on/off on PC token was immediately pushed to client.

Attached is sample campaign saved in 1.3b91 format for testing. Let me know if I missed something?

[Lighting isn't immediately forcing to client #15.zip](https://github.com/JamzTheMan/maptool/files/1290769/Lighting.isn.t.immediately.forcing.to.client.15.zip)

**Comment by JamzTheMan** [comment]
This should be fixed as of commit 9c82797d5f5c7485e297bda38721e58c471995d4
