### ISSUE TITLE
Lights are not updating properly based on ownership

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/maptool#21]
Reported here: http://forums.rptools.net/viewtopic.php?f=3&t=27164

Looks like lights with no ownership are not updating the FoW properly when moved.  Looks to be an issue with new 'ownership' code.

**Comment by dorpond** [comment]
I spent about 15 minutes testing this and it appears fixed. When I initially tested this when the issue was brought to the table, it was easy to see the issue at hand, but all seems normal now.

**Comment by JamzTheMan** [comment]
Appears to be fixed along with other code changes. Will reopen if able to duplicate again.
