### ISSUE TITLE
Maptools (1.4.3.20) won't launch on Mac High Sierra

### ISSUE THREAD

**Issue by dpeet** [JamzTheMan/MapTool#31]
First, thanks for your contributions to this!

I tried to launch Maptools on my Mac running High Sierra, and it fails silently.  I did some searching and it might be due to https://stackoverflow.com/questions/46438558/unable-to-launch-jwrapper-under-macos-high-sierra.  

Thanks!

**Comment by JamzTheMan** [comment]
Hmm, ya, I'm done with jWrapper, especially since they went behind a paywall...

I should be releasing a new 1.4.0.0 version that uses Oracle's packaging and will have a .dmg & .pkg versions.  If you want to test a beta version let me know.

**Comment by dpeet** [comment]
Yeah that's about what I was reading. I'm totally down to beta test if you can send it my way @

**Comment by JamzTheMan** [comment]
Cool, I need more Mac/Linux testers. Especially Mac because VM's are touchy...

If you are in the testing mood, check out http://tokentool.nerps.net/  😄 
It's using the same new packaging and rewritten in FX!

**Comment by dpeet** [comment]
Looks like that loaded!  Do you have the 1.4 version of maptools available as well?

**Comment by JamzTheMan** [comment]
Soon... :)  (I'll try and build it now, Travis can take 15 mins though for Mac build)

**Comment by dpeet** [comment]
Sounds good!

**Comment by dpeet** [comment]
@JamzTheMan I saw the source code get released, but not dmgs.  Should I look somewhere special for that?

**Comment by JamzTheMan** [comment]
I'm still working on it... I have CI issues I'm ironing out still...

**Comment by dpeet** [comment]
Oh no problem! Good luck!

**Comment by dracwyrm** [comment]
@JamzTheMan I can confirm that the 1.4.4.0 branch is working on Gentoo Linux, but with a few tricks that need to be done. :D

**Comment by JamzTheMan** [comment]
OK, finally got the Windows & Linux installs to build via CI (I also post the JAR for manual operation)

Now, once Travis gets done with the MacOS backlog, hopefully that will build sometime today...

https://travis-ci.org/JamzTheMan/MapTool/jobs/309727190

**Comment by JamzTheMan** [comment]
ok, give this a try: https://github.com/JamzTheMan/MapTool/releases/tag/1.4.4.0b8

**Comment by dracwyrm** [comment]
@JamzTheMan Small request, for Linux, would you be able to place the MapTool.desktop file in the /usr/share/applications directory so it will appear in the "start" menu of different DEs? That's the only tweak that I'm seeing so far. :)

**Comment by JamzTheMan** [comment]
I can take a look but not sure that's an option with javapackager too. There's a "permissions" options which I know it drives where it gets installed in Windows and I also the Windows setup prompts for install location...but I don't think there are many options for deb.

I wish there was more unification for Linux but between all the flavors and then all the DE's I doubt it'll ever work for 'all' of them.

If you can find a way to do this with Gradle, I'll def integrate it!

**Comment by dpeet** [comment]
looks like it launched on my Mac!  I'll close this for now

For what it's worth, it put it on the desktop instead of in the applications folder which is more normal

**Comment by JamzTheMan** [comment]
Did you use the dmg or pkg?

Where does tokentool land when you install it?

**Comment by dpeet** [comment]
I used the dmg.  tokentool also links to the desktop.  You can see in the below picture what you would see.  A normal installer links to the applications folder instead


![image](https://user-images.githubusercontent.com/4729779/33501250-ef829912-d6a9-11e7-98fe-137f5c1a85a2.png)

**Comment by JamzTheMan** [comment]
Can you try the pkg? I know I tested the tokentool on Mac vm and it installed normally. I didn't try the dmg yet.

**Comment by dpeet** [comment]
maptool.pkg put it in the right place!

**Comment by JamzTheMan** [comment]
Cool. I'm not a Mac expert but for dmg don't u have to drag to application folder to install there?

**Comment by dpeet** [comment]
normally the installer folder (in the image above) would have the app on the left and a link to the application folder, and the drag and drop action causes the app to be installed in the application folder.
