### ISSUE TITLE
Update UI to FX

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#37]
Begin migration of MapTool to Java FX!

- [x] Launch current MapTool App on FX thread
- [ ] Migrate main Menu UI to FX
- [ ] Migrate Toolbar UI to FX
- [ ] Investigate FX Dockable Windows
- [ ] Migrate Dockable Windows to FX
- [ ] Migrate background image tasks to new FX Image class

**Comment by bobifle** [comment]
It really refreshed the look and feel of token tool.  Keep going !

**Comment by bobifle** [comment]
oh boy, can't wait for the 2.0. May the java god be with you.
