### ISSUE TITLE
Can't open Preferences

### ISSUE THREAD

**Issue by Phergus** [JamzTheMan/MapTool#44]
NOTE: This was using the standalone JAR file download.

Attempting to use Edit/Preferences produces the following:
```
java.lang.UnsatisfiedLinkError: jdk.packager.services.userjvmoptions.LauncherUserJvmOptions._getUserJvmOptionKeys()[Ljava/lang/String;
	at jdk.packager.services.userjvmoptions.LauncherUserJvmOptions._getUserJvmOptionKeys(Native Method)
	at jdk.packager.services.userjvmoptions.LauncherUserJvmOptions.getUserJVMOptions(LauncherUserJvmOptions.java:128)
	at net.rptools.maptool.util.UserJvmPrefs.getJvmOption(UserJvmPrefs.java:75)
	at net.rptools.maptool.client.ui.PreferencesDialog.setInitialState(PreferencesDialog.java:871)
	at net.rptools.maptool.client.ui.PreferencesDialog.<init>(PreferencesDialog.java:292)
	at net.rptools.maptool.client.AppActions$13.execute(AppActions.java:575)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:2828)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI.doClick(Unknown Source)
	at de.muntjak.tinylookandfeel.TinyMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
...
```

**Comment by JamzTheMan** [comment]
See issue #28.

**Comment by Phergus** [comment]
Oops.  My bad.

**Comment by JamzTheMan** [comment]
No prob, was on my phone so didn't want to repeat.  I need to capture that error anyhoo in next version.

**Comment by Phergus** [comment]
I notice that the exceptions I'm getting aren't the same as was reported in issue 28 but might be just OS differences.

Adding the packager.dll into the path changes the error but still doesn't work.  The packager.dll needs something else.  I need to get something else in the path apparently.

```
java.lang.UnsatisfiedLinkError: C:\mydocs\Gaming\rptools\MapTool Nerps\packager.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jdk.packager.services.userjvmoptions.LauncherUserJvmOptions.<clinit>(LauncherUserJvmOptions.java:53)
	at jdk.packager.services.UserJvmOptionsService.getUserJVMDefaults(UserJvmOptionsService.java:58)
	at net.rptools.maptool.util.UserJvmPrefs.getJvmOption(UserJvmPrefs.java:74)
	at net.rptools.maptool.client.ui.PreferencesDialog.setInitialState(PreferencesDialog.java:871)
	at net.rptools.maptool.client.ui.PreferencesDialog.<init>(PreferencesDialog.java:292)
```

**Comment by JamzTheMan** [comment]
Does it work is you run. 'gradle run'?

**Comment by Phergus** [comment]
> Does it work is you run. 'gradle run'? 
Nope.  Because I'm not doing this from source.  :)  I thought I had mentioned this before but I see that I didn't.  Sorry.  Again.

I'm using the release jar file from your [website](http://maptool.nerps.net/).  Needed to make sure that my players could run it before attempting to use it for game sessions.

To get the dll in the path I'm starting it with:
`java -Djava.library.path=".\;%PATH%" -jar MapTool-1.4.4.0.jar`

**Comment by JamzTheMan** [comment]
Ah. In that case... The dll isn't in your PATH, I'll update the website today with. Some instructions on running it.

Is there a reason to not use the .exe then? Better for your players as they won't need Java installed then...

**Comment by Phergus** [comment]
The DLL is in the path or the last exception wouldn't have been thrown.  It is specifically telling you that libraries packager.dll depends on can't be found.   Without the DLL present in the path you get the first exception I posted.  My guess is some of the MS Visual C runtime libs.

> Is there a reason to not use the .exe then? Better for your players as they won't need Java installed then...

Several reasons.
1. It uses an installer instead of just being able to unzip it someplace and run from the folder.
2. It put an icon on my desktop without asking permission.
3. It modified my Start Menu without asking for permission or notifying me it had done so.
4. It won't allow for multiple versions to be installed so as to allow users to connect to servers running different versions.

Also Windows Defender thinks its suspect and wanted to block the install.

**Comment by Phergus** [comment]
Taking the various DLLs included in the exe version and dropping them in the folder along with the packager DLL let it work using the command line I gave above.

**Comment by JamzTheMan** [comment]
Odd, I don't have to include the other dll's but I link to the dll from the installed jdk so will have to check that.

FYI obviously that also only gets you around the error. I will have to disable the tab for the JAR version as you will need to set that up yourself.

The jar is there exactly for that reason, some people are picky about that sort of stuff. 

FYI my fork will probably not be for you in that case. I will be up front, there are restful like functions and Sentry.io error reporting so if you the worry type u may want to stick with 1.4.0.5.

**Comment by Phergus** [comment]
I'll definitely be sticking with 1.4.0.5 for our game sessions.

**Comment by dracwyrm** [comment]
> Also Windows Defender thinks its suspect and wanted to block the install.
I got that as well on my Windows system. I run Linux and Windows on separate machines. I had to open Windows Defender to manually add the .exe to whitelist. I had to Google it on how to do it with the WIndows 10 version.

**Comment by JamzTheMan** [comment]
FYI Windows is always going to complain because I can't afford to digitally sign it. But I haven't gotten a specific Defenders warning.

**Comment by Phergus** [comment]
It was weird.  I hadn't seen it with the regular 1.4.1.8 MT release though that was with jwrapper.

I did just get a Windows update last week and maybe it's a new behavior.  Nothing else has popped that up lately and it certainly could be related to the digital signing.

No big deal in the end. If I decide I want to, I can just package up the jar with the dlls in a zip file along with a batch file.  I'm not sure what's in your build versus the 1.4.1.x branch.  But then I don't know what is different between 1.4.0.5 and 1.4.18 so there's that too. lol

**Comment by JamzTheMan** [comment]
You will have to read through the forums to catch up. I have a running thread on what I add to my fork. And pretty much all of that as of a year ago is in the 1.4.1 branch. Craig also has a 1.4.1 forums post.

There are a lot of bug fixes and enhancements added.

**Comment by JamzTheMan** [comment]
OK, now that I've finally got sit in front of the computer (RL issues and all) vs my phone I see the full issue now.  :smile:

I'll keep this open until I fix it in 1.4.4.1.

**Comment by Phergus** [comment]
Definitely let me know if there is something I can do on my end.

**Comment by JamzTheMan** [comment]
I added try/catch around the preferences so if the DLL is not available, the startup tab is now grayed out and unavailable vs throwing an exception.

**Comment by JamzTheMan** [comment]
Apparently this is not 100% fixed. It will be fixed in the next release.

In the meantime, if you are getting this error, you are probably using a JRE. Install and use Java 10 JDK instead and it should launch ok.

**Comment by JamzTheMan** [comment]
Fixed...again...hopefully... :)

https://github.com/JamzTheMan/MapTool/releases/tag/1.4.5.1
