### ISSUE TITLE
Feature request: optional boundary of light sources

### ISSUE THREAD

**Issue by mlangsdorf** [JamzTheMan/MapTool#46]
Currently, if multiple light sources overlap on the same grid point, the colors combine. It can be hard to tell exactly which light sources are overlapping.

I propose adding an optional keyword border to light definitions, which would create a 1 pixel wide black border at the edge of the light source. 

Here's an example: 3 overlapping auras are indistinct and it's not obvious if the signpost token is covered by 1 or 2 auras.
![current](https://user-images.githubusercontent.com/8007405/34320651-c8b0599c-e7c4-11e7-8a79-96bca8eb1e0c.png)

With the border keyword, it's obvious that the signpost is covered by 2 auras.
![withborders](https://user-images.githubusercontent.com/8007405/34320667-04b5c94a-e7c5-11e7-881e-743321f28b4f.png)

**Comment by JamzTheMan** [comment]
It should be doing this 'on hover' of a token IIRC.  I'll look into this and possibly add a shortcut/menu option to toggle it on/off...

**Comment by mlangsdorf** [comment]
I get a white border at the end of vision when I hover over tokens, but if I have multiple overlapping lights or auras, I have get no indication of the boundary.

Also, even if I could get the light boundary when mousing over the token with light source, that's not as useful as always having the boundary for all light sources. I'm not as interested in what any given token's aura covers as I am in what auras cover a specific token.

**Comment by JamzTheMan** [comment]
It may or may not be possible, I will see. lights are "combined" into a single Area (geometry shape) so it depends on how much work this will be...
