### ISSUE TITLE
Maptool ver. 1.4.4.0 Fails to Launch After Changing Settings

### ISSUE THREAD

**Issue by reggiebritten** [JamzTheMan/MapTool#47]
Hi, I seem to running into an error with the latest version of Maptool. The symptom is Maptool simply fails to launch; I double click the MapTool.exe file, and nothing at all happens. This happened immediately after I adjusted the minimum and maximum memory and the stack size. I assume I entered incompatible values, and that is somehow causing Maptool to fail to load. Things I have tried so far include re-installing Maptool, deleting the .maptool folder in my users folder, and deleting the MapTool folder in the Appdata\Local folder. MapTool version 1.4.3.20 still seem to work just fine for me. I hope this feedback helps to identify the issue, Thanks.

**Comment by JamzTheMan** [comment]
Try using the -reset option. See the FAQ for more info:

https://github.com/JamzTheMan/MapTool/wiki/F.A.Q.

**Comment by reggiebritten** [comment]
I'm glad to see that the FAQ already covers this issue, but it looks like the -reset option does not work for me. I made a shortcut with this target: "C:\Users\Reggie\AppData\Local\MapTool\MapTool.exe -reset" and running that shortcut doesn't seem to do anything at all either. Running the normal shortcut and deleting folders/reinstalling don't seem to change anything either.

**Comment by JamzTheMan** [comment]
OK, i"ve updated the [F.A.Q.](https://github.com/JamzTheMan/MapTool/wiki/F.A.Q.) to include the location of the cfg file.  Try manually editing the file and see if that helps?

I'm looking into a better solution to reset but I'm limited in what I can do with the native launchers.

**Comment by reggiebritten** [comment]
Yep, it looks like editing the jvmuserargs.cfg solved the problem! I opened the file in notepad and changed the numbers to what you recommend in the FAQ and now everything seems to be working fine.

I suppose that's not really a problem unless someone likes me breaks things in the first place, but it's nice to know how to fix it if it does happen. Thanks for your help!

**Comment by JamzTheMan** [comment]
Great! No problem.
