### ISSUE TITLE
Failed to Create JVM

### ISSUE THREAD

**Issue by Durnn** [JamzTheMan/MapTool#50]
When i first launched the 1.4.4.0.exe, I loaded a framework that was throwing stack errors.  I changed the settings within the preferences to 2024 512 3.  Since then I am unable to launch the .exe because it gives me a error saying Failed to Create JVM followed by a Failed to Launch JVM.  I have tried to uninstall maptools but it gives same errors even after reinstalling. I am assuming there may be some left over pref files that I am missing.

Side note, I can launch it with the .jar file.  I guess since it uses different java files?

**Comment by JamzTheMan** [comment]
Are you still having this issue and did you try the suggestions in the FAQ?

https://github.com/JamzTheMan/MapTool/wiki/F.A.Q.!

**Comment by Durnn** [comment]
I just switched to a different version of Maptools.  Thank you anyways.  Also that link sends me to a page to create a new page?

**Comment by JamzTheMan** [comment]
no problem. And corrected the link, github didn't autocreate the link and shortened it...
