### ISSUE TITLE
Missing Preferences menu option on OS X

### ISSUE THREAD

**Issue by ErikWPotter** [JamzTheMan/MapTool#54]
1.4.4.1 no longer shows the Edit>Preferences menu option on OS X.

It was there in 1.4.4.0 and is still there in 1.4.4.1 on Windows.

**Comment by JamzTheMan** [comment]
Well that is down right wierd... I will look into it.

**Comment by JamzTheMan** [comment]
I put a hotfix out for OS X if you would like to test and confirm this fixes the issue.

https://github.com/JamzTheMan/MapTool/releases/tag/1.4.4.2

**Comment by ErikWPotter** [comment]
Confirmed on my end.
