### ISSUE TITLE
java startup parameters

### ISSUE THREAD

**Issue by GmMalleg** [JamzTheMan/MapTool#62]
it is possible to lock yourself out of maptool by setting an insufficient stack size.
also being the configuration file for java  in "$HOME/.local/net.rptools.maptool.client/packager/" removing .maptool-nerps did not resolve anything.

in the end, I resolved by manually editing the file jvmuserargs.cfg.

**Comment by JamzTheMan** [comment]
Yea, I can't really do anything about that. If you entered in bad jvm parameters, it will not load. 

I have no way of knowing what would be bad parameters for your system so the only solution is what you did, edit/delete the cfg.

**Comment by GmMalleg** [comment]
I understand, would it be impossible to move the cfg into the .maptool-nerps folder? it would make things easier for less tech-savvy users.

**Comment by JamzTheMan** [comment]
It would not. The native executable is created by oracle's javapackager and used internal means to read/write to that cfg. I have no control over that piece of code.
