### ISSUE TITLE
Restore default behavior of spacebar+left mouse click

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#63]
Not all users like the map auto centered when GM clicks spacebar to show arrow/thought bubble/speech bubble.

**Comment by bobifle** [comment]
As an alternative you could center only if the arrow is out of the client current area.

**Comment by JamzTheMan** [comment]
Spacebar functionality  has been restored to it's original behavior due to hatred 👿 
This includes ctrl+spacebar & shift+spacebar as well.

<br>

![look_here](https://user-images.githubusercontent.com/8051654/41138737-efa03b46-6aa8-11e8-9027-86f6c93c0db3.png)
A new shift+ctrl+spacebar command along with a new pointer image is now available. When this keystroke combo is pressed, and you are a GM, the pointer will center & zoom all connected clients to that point. When it is released, all clients will return to their previous view point & zoom.
