### ISSUE TITLE
Non-owned tokens reveal soft FoW when server IView/IFoW is off for Player view

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#64]
Reported: http://forums.rptools.net/viewtopic.php?f=3&t=27591

When server setting is not using IFoW, non-owned NPC tokens are revealing soft FoW for Player Clients.

Campaign Oryan77_Bad_FoW.cmpgn shared for testing.

**Comment by RicoTheBold** [comment]
I am also encountering this issue and can provide indications of what settings/campaign I use.
