### ISSUE TITLE
Token VBL out of alignment on rotation

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#7]
Reported by Wolph42

> In 1.4.3.20, the yellow vbl turned on for a long stretched token is rotated a bit
![image](https://user-images.githubusercontent.com/8051654/29221333-ff16935c-7e83-11e7-8c3a-8b488eee48b3.png)

https://files.slack.com/files-pri/T0RQMKMEK-F6LKWFT7S/download/jamz_bugged_campaign_file.cmpgn

**Comment by dracwyrm** [comment]
I've just been through the VBL yesterday looking at this, because I noticed it in some of my maps, but on shorter objects like doors. I was also looking for the reason that sometimes VBL would be left behind when I rotate or move a door.

**Comment by JamzTheMan** [comment]
Are you sure its vbl left behind and not FoW.  When you move a token, fow is not refreshed on purpose so you have to do that in your macro or manually. 

If it vbl, take a screenshot.

_Sent from my Samsung SM-G860P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
