### ISSUE TITLE
Cannot deactivate the templates "snap to grid"

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#74]
Clicking on the button seems to have no effect.
Should be easy to reproduce.

**Comment by JamzTheMan** [comment]
Eh? I thought they always snapped to grid? What am I missing?

**Comment by JamzTheMan** [comment]
Ah. I forgot about that button, never used it.  So it sticks? Will have to see how long that has been happening...

**Comment by bobifle** [comment]
As an alternative, you could disable de button when templating, it could be a cheaper solution than implementing non snapped templates.
