### ISSUE TITLE
Hitting shift while using templates should delete the templates

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#75]
This is a suggestion for a minor enhancement:

When setting VBL and FOW, hitting shift reverse the command, reveal becomes hide, we could use the same approach for templates and thus get a consistent way of doing and undoing things in maptool.

**Comment by bobifle** [comment]
I know what fools me, with FOW you must hit shift on the first click (when drawing rectangles). For templates, shift must be hit on the second click (the one that ends the template).

I remember being puzzled by the FOW way of doing at the beginning. From a user PoV, I think any shift pressed, weither it's on the first second or any click during the shape should trigger the reverse command.

**Comment by JamzTheMan** [comment]
I'll look into this when I can, if we can ever replicate it more reliably it'll help.

**Comment by JamzTheMan** [comment]
Sounds about right. Changed this to an enhancement but sounds like a reasonable user interface request to keep things uniform.
