### ISSUE TITLE
Cell Highlight distance text not sizing for grid sizes

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#81]
When moving tokens, distance to that cell is displayed, but not resized properly when grid size is something other than default 50.

**Comment by Phergus** [comment]
Did you notice in that one map experiencing the slowdown that for large Distance per Cell values the distance quickly starts overflowing.  Probably related to this.

**Comment by Phergus** [comment]
Pic to explain babbling.
![screenshot 2018-06-25 06 03 01](https://user-images.githubusercontent.com/34379254/41931393-2cfa7dee-793b-11e8-9d61-3a6498ee3098.png)

**Comment by JamzTheMan** [comment]
Yep. That's when I noticed it so thought I'd put an issue to remind myself... :) On the other side, changing the grid size to, say, 150, makes the text really really small.

I already handle resizing text on zoom, will be an easy fix...
