### ISSUE TITLE
Stat sheet displayed only when SHIFT is pressed upon entering the token

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#84]
Rather minor, but quite annoying to be honest.

When your mouse is over a token and you hit shift to display the sheet, it does not work. You have to move out and back in to make the sheet pop.

Ofc, you need to check the MT preference "stat sheet displayed when shift pressed"

**Comment by JamzTheMan** [comment]
may be an easy fix...may not be an easy fix...

The "Pointer" class is kinda all over the place checking for shifts and clicks and drags and all that... I'll take a look next time in there but no guarantees.
