### ISSUE TITLE
Error: java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds

### ISSUE THREAD

**Issue by auror92** [JamzTheMan/MapTool#93]
When i try to execute a macro that has this line of code [H: abort(input(json.toList(inputStr,"##")))] i get the error: <br>
java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds errore nell'esecuzione dell'espressione abort(input(json.toList(inputStr,"##"))). 

I think this happens since i installed an update, can't remember which, maybe from 1.4.4.1 to 1.4.4.2. I get the error only on maps created or modified with the new versions, old maps on the campaign file work fine as long as i don't edit them.

**Comment by JamzTheMan** [comment]
I would need to see the inputStr and/or the campaign file to debug this. (FYI small files can be drag and dropped to issues as attachments)

This looks like a normal macro error as no changes to macros have been done. Unless it's an language issue? (if you set MapTool to English via Edit -> Preferences -> Startup) and restart MT, does the issue remain?

**Comment by auror92** [comment]
Tried setting english but didn't solve the issue. The strange thing is that i get no errors on "library" map and old maps created with previous versions of nerps MT. I forgot to mention i play on linux, does that make any difference? 
This is the campaign file:
 https://mega.nz/#!nHwl3C5T!nyi-Aoz8wQgLOtGZta-PcLI61us4DEkymQP-0er6Ofg

It's a 5e framework from the rptools forum that i modified for my needs, you maybe know the one i'm talking about(i'm no expert at coding so my edits are probably horrible to look at). Anyway the macro is "_aliasmaskAttack" on Lib:CharacterSheet; i use it to make an attack on NPC tokens. Thank you hope you can find the problem.
