### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by FROST-D** [JamzTheMan/MapTool#94]
hi Jamz,

I would like to get into official coding of maptool.
Right now i only added some new macro functions (cause of performance issue with macro coding) needed for a campaign where i created a character sheet for my players with HPbar\Manabar\Stats\Char Active States\Equipment all refreshing with token properties.
Now i'd like to work on the possibility to add some API to comunicate with an Android APP i made.

1- It is better to ask RPTools first about the API ?
2- It is better to fork your work or fork the official mapTool repository ?(i am actually using your maptool)
3- Can i use IntelliJ IDEA as IDE or Eclipse is mandatory ?

ty again for your time and for your great job with this application

**Comment by JamzTheMan** [comment]
Sorry, didn't see this until now.  For now I would start off with the main RPTools repo and present your API there for discussion. There is a great knowledge base there and may turn into a better discussion.

Anything you build there *should* also work in my fork. Currently the major difference is I have brought in the RPLib code base internally in my fork so would just have to be mindful to any references to that package (although I'm trying to get that moved in the main repo as well in a future version).

Depending on a few things, you may be able to develop under my for and submit a PR upstream still as well.

And sure, use what ever IDE you wish. We're trying to keep it IDE agnostic but currently our Gradle build does support Eclipse by the way of creating the necessary files needed IF you run the 'eclipse' task.  Just be sure to add any IntelliJ specific files to the .gitignore and don't check them into GitHub (you will notice we do not check in any Eclipse specific project/classpath files)

You will probably want to add the IDEA plugin to the gradle build first and get that going first. There shouldn't be an issue merging that into our normal build file as well (I just haven't used IntelliJ in over 10 years myself) as it shouldn't do anything unless invoked (if it's like the Eclipse plugin)

https://docs.gradle.org/current/userguide/idea_plugin.html

**Comment by JamzTheMan** [comment]
Trying new github plug in and will move this issue to main repo. :)

/move to RPTools/maptool
