### ISSUE TITLE
New images dropped on map and immediately moved, revert back after a few seconds

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#99]
**Describe the bug**
New tokens/objects dropped on the map takes a variable time (seems to be based on size of file) to sync to the default server (guessing here). If the token is changed (eg moved or edited) those changes are lost when the "view" is updated (after unknown processes is finished).

**To Reproduce**
1. Go to a new map/campaign
2. Clear asset cache for clean testing
3. Drop image to map, larger the better, e.g. 1-5 Mb images
4. Immediately move image several cells over (or edit properties via macro)
5. Wait 1-30 seconds for image to move back to original location (or properties to revert)
6. Repeat steps 3-5 (can do 3-4 multiple times then step 5)

**Expected behavior**
Changes should NOT revert

**Screenshots**

**MapTool Info**
- Version: 1.5.4.3 (also tested in 1.4.1.8 and 1.4.0.5)
- Install: Multiple by multiple users

**Desktop (please complete the following information):**
 - OS: All
 - Version All

**Additional context**
None should be needed, can be reproduced by developers.
Suspect asset/cache related? Currently can only reproduce if image has not been cached yet, once cached it is not happening

**Comment by Phergus** [comment]
Drawing tools display same issue.  If a large (2k x 2k) texture is selected for the pen color when drawing, when the drawing is complete it will disappear and then re-appear after a few seconds.  Once a texture has been used to draw, subsequent drawings behave as expected.  Tested with free-hand drawing tool.  No fill color/texture.   Just pen texture.
